### ISSUE TITLE
Addition to runblender.ipynb

### ISSUE THREAD

**Issue by jujubeesloco** [donmahallem/colab_blender#15]
Sorry, I am a novice to pull requests and forking, so decided this way to communicate.

I've added Python Virtual Display and changed the paths of mounting google drive to make them navigable in Colab's U.I.

To have a look:

[https://github.com/jujubeesloco/Colab-and-Snippets/blob/master/runblender.ipynb](url)

Again, sorry for the method of communication,

-jujubeesloco

**Comment by donmahallem** [comment]
Hi, thanks! 

I will have a look at it tomorrow and merge it if it looks fine to me

Normally you would fork this repo, add your changes and create a pull request from you cloned repo to mine. It should be in the GitHub docs too
