### ISSUE TITLE
Change tile size doesn't work.

### ISSUE THREAD

**Issue by arun54321** [donmahallem/colab_blender#2]
I edited the setgpu script to change tile size like this. but it doesn't work.

```
    except TypeError:
        pass
for scene in bpy.data.scenes:
    scene.render.tile_x = 256
    scene.render.tile_y = 256
# Enable all CPU and GPU devices
for device in cprefs.devices:
    if not re.match('intel', device.name, re.I):
        print('Activating',device)
        device.use = True
```

**Comment by donmahallem** [comment]
I havent encountered that specific issue. Never had issues changing the tilesize in the script? Which blender version do you use? If I do lookup the [documentation](https://docs.blender.org/api/current/bpy.types.RenderSettings.html#bpy.types.RenderSettings) it should just work with up to the latest version. 

My first Idea would be: Did you rerun the cell with the changed values in the script? You need to rerun the cell EVERY time you edit it as it gets persisted to the disc. Run blender after.

**Comment by arun54321** [comment]
> Did you rerun the cell with the changed values in the script? 

Yes. I used blender 2.82.

**Comment by donmahallem** [comment]
Could you print out the tile_x and tile_y values after they are set? If they are set as expected? It's a little hard for me to debug this from a guesses.

**Comment by arun54321** [comment]
I changed to blender 2.83.0. It works now. I don't know why it didn't work before. Thanks.
