### ISSUE TITLE
Error: sudo: ./blender2.91.2/blender: command not found

### ISSUE THREAD

**Issue by ASOwnerYT** [donmahallem/colab_blender#22]
# 🐞 bug report

### What is your issue
 When I run the script in Blender Collab, at the bottom of the notebook I get the error: sudo: ./blender2.91.2/blender: command not found

Also I get this error on the second cell:
--2021-02-03 05:00:37--  https://ftp.halifax.rwth-aachen.de/blender/release/Blender2.91/blender-2.91.2-linux64.tar.xz/
Resolving ftp.halifax.rwth-aachen.de (ftp.halifax.rwth-aachen.de)... 137.226.34.46, 2a00:8a60:e012:a00::21
Connecting to ftp.halifax.rwth-aachen.de (ftp.halifax.rwth-aachen.de)|137.226.34.46|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-03 05:00:37 ERROR 404: Not Found.

tar: This does not look like a tar archive

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now

### What Blender Version are you using?

2.91.2

### What Render Engine are you using?

 Cycles

### What addons are you using?

 No Blender addons were used

**Comment by donmahallem** [comment]
This might be my bad. I need to find a better way to extract the blender versions. Give me an hour and it should be fixed !

**Comment by donmahallem** [comment]
So there was a trailing slash that broke the download path. You will need to reset the runtime to factory settings.

Could you verify my fix on this [branch](https://github.com/donmahallem/colab_blender/tree/fix/issue/22) before I merge this to master?

**Comment by ASOwnerYT** [comment]
It downloads fine now. Not sure if it's related to this issue, but now I get this error at the bottom: Error: Cannot read file '/gdrive/My Drive/subscribe': No such file or directory

I'm trying to make the output files go in a folder in My Drive, so is this a bug or am I just doing something wrong?

**Comment by donmahallem** [comment]
Did you mount your GDrive correctly. Expand the left side bar and open the file explorer in colab. See if there is such a path?
