### ISSUE TITLE
Not able to use commands -s and -e for 2.82a render

### ISSUE THREAD

**Issue by Quvance** [donmahallem/colab_blender#4]
# 🐞 bug report

### Suspected bug?

Moved this to repository as suggested in thread.

I have a rather complicated file to render with fog (principled volume shader) and water ripples, and each frame takes about 2 hours to render. I lost connection to Google cloud a few times but could not start from the next frame.

The commands -a and -f 1 work well for rendering but e.g.  -s 2 does not work. Is this a bug?

I would also like to take some suggestion on speeding up the render process. Don't think I can bake any of the above. Other settings to tweak?
 

### What Blender Version are you using?

2.82a

### What Render Engine are you using?

Cycles.

### What addons are you using?

Various. Node wrangler etc

**Comment by donmahallem** [comment]
I am currently on the move and can't verify it myself.

I might not have specified it well enough but if you use -a you leave out the -f command and provide -s startFrame and -e endFrame. So you will always have to specify either -a or -f and you can amend -a with -s and -e


If you do provide the -f command it will just render that specific frame. What is your complete cli command?

**Comment by Quvance** [comment]
OK I didn't realise that. I foolishly used just -s without the -a before. Will try again after the next disconnect from the cloud. Thanks for clarification.

**Comment by donmahallem** [comment]
No problem. I missed that parameter too  
before. If this solved the issue please mark this issue as closed.

**Comment by Quvance** [comment]
Still not working. I specified -a -s 4 but it renders from frame 1 on that
basis not frame 4.

**Comment by donmahallem** [comment]
With my demo project I couldn't reproduce this bug. Would you mind trying to use a default cube project and see if you can reproduce it? So we can exclude the possibility that something inside the project is at fault?

**Comment by Quvance** [comment]
OK this is sorted now. Many thanks. I got the order wrong. -s 4 -a works
now as intended.

**Comment by donmahallem** [comment]
Oooh, you are totally right. I could have thought of that... In blender commands are order agnostic. They will be executed in order they are specified. That's why you specify the python script after the blend file.. had my own issues with this before but didn't have it on my mind
