### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Raimund58** [donmahallem/colab_blender#5]
Since the is no way to contact you directly over GitHub it go this way. 

Again, thank you for your awesome script! 
I modified it a bit. Take what you want. :)
For example is EEVEE rendering now possible :D
(Was previously not possible because EEVEE does not work on headless machines)
https://colab.research.google.com/gist/Raimund58/88061f785ea2563d345914d196c15b87/blender_script_for_google_colab_using_the_gpu.ipynb

**Comment by donmahallem** [comment]
I will look into it once I have some spare time. You can open a PR Request against this Repo with your modifications too and I will merge it if have looked into it.
