### ISSUE TITLE
Is it possible to run 2.90 and higher blend files?

### ISSUE THREAD

**Issue by zakharsvst** [donmahallem/colab_blender#9]
This is my end result.
I am using the latest blender version, which is 2.90.1
![Знімок екрана 2020-10-10 233023](https://user-images.githubusercontent.com/72671563/95664685-cbd6ae00-0b52-11eb-9f11-f45c401eea98.png)

**Comment by donmahallem** [comment]
I would have to expand the script for a selector for blender 2.90. I am currently on the move and wouldn't be able to do this until earliest tomorrow.

In the mean time you could modify the script yourself to download and run 2.90 instead by using https://ftp.halifax.rwth-aachen.de/blender/release/Blender2.90/blender-2.90.1-linux64.tar.xz as download url instead

**Comment by jujubeesloco** [comment]
Is the ram full?
It's rendering, so your download of blender is correct? Each frame is using 7gb-ish of Ram...?

In case; sourced from the closed issues:

-------------For more Ram-------->
(Note: crashes Colab's 12gb of Ram, Colab then offers 25gb):

a = []
while(1):
a.append('1')

----------------


Cheers!

P.s. mr. don's url is top... in case:    
      https://www.blender.org/download/Blender2.90/blender-2.90.1-linux64.tar.xz/

**Comment by zakharsvst** [comment]
I changed the script to download and run 2.90 like mr. don said, and it gave me much better results. 
BUT it looks like the Ram is full, it reaches the point of using 12gb of 12gb available and crashes again. 

@jujubeesloco can you please explain what is needed to do in order to increase the amount of Ram, because I don't understand this one at all.
Thank you in advance.

**Comment by jujubeesloco** [comment]
a = []
while(1):
a.append('1')  


The above was used to cause an infinite loop to crash and then be offered more ram. However, this may be outdated, not consistent, or upgrading ram may no longer be possible.

This link may help(though haven't tried it myself):

https://medium.com/@techhawa/increase-google-colab-ram-from-12gb-to-25gb-211bb5bf08ba

Please keep us informed you find a solution. Thanks!

**Comment by donmahallem** [comment]
I don't know if the behavior was changed but you could Termine Machines over and over until you get a better GPU a while back before they offered the paid tier.

Just use !nvidia-smi to check which gpu and capabilities you got.

**Comment by donmahallem** [comment]
Hi!

I created #11 and would appreciate someone else testing it before I merge it. It should offer 2.91 blender as an option.
